name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout code
        uses: actions/checkout@4

      # 2. Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, bcmath, curl, zip, gd

      # 3. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 4. Install PHP dependencies
      - name: Install Composer dependencies
        uses: |
          composer install --no-dev --optimize-autoloader --no-interaction

      # 5. Build assets
      - name: Build assets
        run: |
          npm ci
          npm run build

      # 6. Deploy to server
      - name: Deploy to Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: nourya
          key: ${{ secrets.SSH_KEY }}
          script: |
             cd /var/www/nouryavoyage
             git pull origin main
             composer install --no-dev --optimize-autoloader --no-interaction
             npm ci
             npm run build
             php artisan optimize:clear
             php artisan config:cache
             php artisan route:cache
             php artisan view:cache
             sudo systemctl reload nginx
